# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0019_auto_20170815_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
